### ISSUE TITLE
Historic and Cultural Textile and Apparel Collection (textile-and-apparel)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#626]
**Item Count:** 2403 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** 
https://github.com/OregonDigital/OD2-migration/blob/master/textile-and-apparel/textile-and-apparel_aa.txt
https://github.com/OregonDigital/OD2-migration/blob/master/textile-and-apparel/textile-and-apparel_ab.txt
https://github.com/OregonDigital/OD2-migration/blob/master/textile-and-apparel/textile-and-apparel_ac.txt
https://github.com/OregonDigital/OD2-migration/blob/master/textile-and-apparel/textile-and-apparel_ad.txt
https://github.com/OregonDigital/OD2-migration/blob/master/textile-and-apparel/textile-and-apparel_ae.txt

**Comment by carakey** [comment]
@wickr :

The one non-English AAT term flagged on #627 was the only irregularity I saw, looking through the facet list in the un-reviewed items.
Otherwise, except for the missing Collection field and the incorrect display label for "Designer Label" - https://github.com/OregonDigital/OD2/issues/2570, all HCTAC batches look good and are all ready for batch approve.

**Comment by wickr** [comment]
label fixed in aa batch.
All batches approved.

**Comment by wickr** [comment]
2403 public count matches original.
All batches look good, closing this as completed.
