### ISSUE TITLE
Columbia Gorge Discovery Center Photo Archive (columbia-gorge)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#835]
**Item Count:** 8,435 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/columbia-gorge/columbia-gorge_pids.txt

**Comment by carakey** [comment]
I'm seeing a lot of non-EDTF dates in Date Created, like 1890-1900's. (I thought these were getting screened in migration.) Seems 100% fine to remediate later but wanted to note it.

**Comment by carakey** [comment]
Finished QA. 
We can come back to the non-EDTF dates in comment above, and also to the “.octet-stream” extension on some of the JPEG 2000 files.
One item in batch _ab / #837 had high-res download allowed - I didn't see any other irregularities. That might want looking into, but otherwise would be ready for batch approve. 
@wickr

**Comment by wickr** [comment]
Yeah I left the EDTF dates in there for now, to remediate later.
Agreed we can improve and/or convert the JPEG 2000 files.
Noted in the _ab ticket but I didn't find any other works with high res download allowed set.
All works reviewed and counts look good.
